### ISSUE TITLE
Error using latest RetinaTag plugin w/ latest AssetPipeline

### ISSUE THREAD

**Issue by ikakara** [bertramdev/retina-tag-grails#2]
compile ":asset-pipeline:2.1.1"
    compile ":retina-tag:2.1.0"

2015-02-17 19:10:57,760 [localhost-startStop-1] ERROR plugins.DefaultGrailsPluginManager  - Error configuring dynamic me
thods for plugin [retinaTag:2.1.0]: No bean named 'asset.pipeline.AssetsTagLib' is defined
Message: No bean named 'asset.pipeline.AssetsTagLib' is defined

**Comment by davydotcom** [comment]
Fixed in version 2.1.1
